server:
  port: 8080
  servlet:
    context-path: /emall



spring:
  profiles:
    active: prd
  datasource:
    username: root
    password: carrotsql321
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.48.246:3309/e-mall?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#mybatis:
#  # 指定全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
#  # 指定sql映射文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml #mapper文件路径
  configuration:
    map-underscore-to-camel-case: true #是否启用驼峰命名（Mybatis默认属性名和数据库一致）,驼峰模式：例如userCode，数据库对应的就是user_code
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
  type-aliases-package:  com.carrot.emall.enetity #Mybatis扫描的业务实体
  global-config:
    db-config:
      id-type: id_worker_str
      #数据库大写下划线转换
      capital-mode: true
      #配置逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0

---
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8080
spring:
  profiles: prd
---