server:
  port: 8080
  servlet:
    context-path: /film



spring:
  profiles:
    active: prd
  datasource:
    username: root
    password: carrotsql321
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.48.246:3309/film?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
---
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8080
spring:
  profiles: prd
---